ansible_user: ec2-user
ansible_password: DevOps321
env: dev
dns: opswithvyas.online
REDIS_HOST: redis-dev.opswithvyas.online
MYSQL_HOST: mysql-dev.opswithvyas.online
MONGODB_HOST: mongodb-dev.opswithvyas.online
RABBITMQ_HOST: rabbitmq-dev.opswithvyas.online

CATALOGUE_HOST: catalogue.backend-alb-dev.opswithvyas.online
USER_HOST: user.backend-alb-dev.opswithvyas.online
CART_HOST: cart.backend-alb-dev.opswithvyas.online
SHIPPING_HOST: shipping.backend-alb-dev.opswithvyas.online
PAYMENT_HOST: payment.backend-alb-dev.opswithvyas.online