[local]
localhost

[mongodb]
mongodb-dev.opswithvyas.online

[redis]
redis-dev.opswithvyas.online

[mysql]
mysql-dev.opswithvyas.online

[rabbitmq]
rabbitmq-dev.opswithvyas.online

[catalogue]
catalogue-dev.opswithvyas.online

[shipping]
shipping-dev.opswithvyas.online

[cart]
cart-dev.opswithvyas.online

[user]
user-dev.opswithvyas.online

[payment]
payment-dev.opswithvyas.online

[frontend]
roboshop-dev.opswithvyas.online